# Generated by Django 5.1.6 on 2026-02-22 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_branches_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Session duration in minutes (60 or 90)', validators=[django.core.validators.MinValueValidator(30)]),
        ),
    ]
