# Generated by Django 5.1.6 on 2026-02-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='benefits',
            field=models.TextField(blank=True, help_text='Key benefits of this service, separated by newlines.'),
        ),
    ]
