# Generated by Django 4.2.27 on 2026-02-25 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(help_text='Session duration in minutes (30 or 45)', validators=[django.core.validators.MinValueValidator(30)]),
        ),
    ]
