# Generated by Django 4.2.27 on 2026-02-28 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_update_durations_30_45'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(choices=[(30, '30 Minutes'), (45, '45 Minutes'), (60, '60 Minutes'), (90, '90 Minutes')], help_text='Session duration in minutes', validators=[django.core.validators.MinValueValidator(30)]),
        ),
    ]
