# Generated by Django 5.1.6 on 2026-02-21 02:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='workers/')),
                ('bio', models.TextField(blank=True)),
                ('specialties', models.CharField(blank=True, help_text='Comma-separated specialties shown on profile card', max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Worker',
                'verbose_name_plural': 'Workers',
                'ordering': ['branch', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkerLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_date', models.DateField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Worker Leave',
                'verbose_name_plural': 'Worker Leaves',
                'ordering': ['-leave_date'],
                'unique_together': {('worker', 'leave_date')},
            },
        ),
        migrations.CreateModel(
            name='WorkerSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Worker Schedule',
                'verbose_name_plural': 'Worker Schedules',
                'ordering': ['worker', 'weekday'],
                'unique_together': {('worker', 'weekday')},
            },
        ),
    ]
