# Generated by Django 5.1.6 on 2026-02-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='specialties',
        ),
    ]
