# Generated by Django 5.1.6 on 2026-02-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_remove_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
