# Generated by Django 5.1.6 on 2026-02-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_worker_years_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='photo',
        ),
    ]
