# Generated by Django 4.2.27 on 2026-02-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_remove_worker_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='location',
            field=models.CharField(blank=True, help_text='Where the therapist operates (e.g. Home Service, South Mumbai)', max_length=255),
        ),
    ]
