# Generated by Django 5.1.6 on 2026-02-21 02:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('guests', '0001_initial'),
        ('services', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('booking_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Actual booked duration (service.duration_minutes at time of booking)')),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING_PAYMENT', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('WAIVED', 'Waived (Admin)'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('access_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('is_manual', models.BooleanField(default=False, help_text='True if created by admin on behalf of customer (payment waived)')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='branches.branch')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='guests.guest')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-booking_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=20)),
                ('to_status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=20)),
                ('changed_by', models.CharField(help_text='system / admin / webhook', max_length=80)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Booking Status Log',
                'verbose_name_plural': 'Booking Status Logs',
                'ordering': ['changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SlotLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('released', models.BooleanField(db_index=True, default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_locks', to='branches.branch')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_locks', to='workers.worker')),
            ],
            options={
                'verbose_name': 'Slot Lock',
                'verbose_name_plural': 'Slot Locks',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='slot_lock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='bookings.slotlock'),
        ),
        migrations.AddConstraint(
            model_name='slotlock',
            constraint=models.UniqueConstraint(condition=models.Q(('released', False)), fields=('worker', 'booking_date', 'start_time'), name='uq_active_slot_lock'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CONFIRMED')), fields=('worker', 'booking_date', 'start_time'), name='uq_confirmed_booking_slot'),
        ),
    ]
