# Generated by Django 5.1.6 on 2026-03-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hidden_from_dashboard',
            field=models.BooleanField(db_index=True, default=False, help_text='Hides this booking from the admin dashboard view (data is preserved in DB)'),
        ),
    ]
