# Generated by Django 5.1.6 on 2026-02-22 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_branch_closing_time_branch_opening_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='working_days',
        ),
        migrations.CreateModel(
            name='BranchSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_open', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='branches.branch')),
            ],
            options={
                'ordering': ['weekday'],
                'unique_together': {('branch', 'weekday')},
            },
        ),
    ]
