# Generated by Django 4.2.27 on 2026-02-25 02:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('client_name', models.CharField(max_length=100)),
                ('instagram_url', models.URLField(help_text='Paste the Instagram Reel or Post URL (e.g., https://www.instagram.com/reels/XYZ/)')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
